### ISSUE TITLE
Noxon Login Token Hashing

### ISSUE THREAD

**Issue by veso266** [cweiske/noxon-gateway#1]
Hi here: https://cweiske.de/noxon-api.htm#id14 you mentioned that when radio request: http://radio567.vtuner.com:80/setupapp/radio567/asp/BrowseXPA/LoginXML.asp?mac=6FD0281BB8B2C3D46ABB2A34CA9EF1CF&fver=3.8.36.6921&dlang=ger&hwid=13062&startitems=1&enditems=10 it 

it appeds mac= parameter to http://radio567.vtuner.com:80/setupapp/radio567/asp/BrowseXPA/LoginXML.asp but the MAC adress it appends is hashed with token it gets from here: http://radio567.vtuner.com:80/setupapp/radio567/asp/BrowseXPA/LoginXML.asp?token=0

so I wonder did you ever figure out what hasing algorithm it uses to hash this token: a6703ded78821be5 into this MAC: 6FD0281BB8B2C3D46ABB2A34CA9EF1CF (for later appending it into here: http://radio567.vtuner.com:80/setupapp/radio567/asp/BrowseXPA/LoginXML.asp

Thanks for Anwsering and best Regards

**Comment by cweiske** [comment]
No, I never worked on that.
