### ISSUE TITLE
Noxon iRadio remote control

### ISSUE THREAD

**Issue by ThomasHeinrichSchmidt** [cweiske/noxon-gateway#2]
I have programmed a iRadio remote control for the PC [NOXON iRadio](https://github.com/ThomasHeinrichSchmidt/iRadio) - actually everything that can be done with the manual radio remote control is possible - just via the (local) network. 
In this way you can control the noxon-gateway from your PC without even going near the iRadio.

**Comment by cweiske** [comment]
Nice.

What do you expect from me?

**Comment by ThomasHeinrichSchmidt** [comment]
Thanks for your feedback. I would just like to make the app a bit more popular, there is certainly room for improvement.
Can I perhaps even suggest that you try it yourself?
Cheers
--thomas.

**Comment by cweiske** [comment]
I don't own any iRadio devices anymore, sorry :) My current kitchen radio is a Technisat DigitRadio 580 (http://www.bogo/tagebuch/technisat-digitradio-580.htm).

**Comment by ThomasHeinrichSchmidt** [comment]
I understand, thanks for sharing.
